SELECT CAR.CAR_ID, CAR.CAR_TYPE,
ROUND(CAR.DAILY_FEE * 30 * (1 - COALESCE(PLAN.DISCOUNT_RATE,0)/100),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CAR
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
    ON CAR.CAR_TYPE = PLAN.CAR_TYPE
    AND PLAN.DURATION_TYPE = '30일 이상'
WHERE CAR.CAR_TYPE IN ('세단','SUV')
    AND CAR.CAR_ID NOT IN (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE START_DATE <= '2022-11-30'
                  AND END_DATE >= '2022-11-01')
AND CAR.DAILY_FEE * 30 * (1 - COALESCE(PLAN.DISCOUNT_RATE, 0) / 100) >= 500000
AND CAR.DAILY_FEE * 30 * (1 - COALESCE(PLAN.DISCOUNT_RATE, 0) / 100) <= 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;