-- 작성 순서: SELECT FROM JOIN WHERE GROUP BY HAVING ORDER BY LIMIT
-- 해석 순서: FROM JOIN WHERE GROUP BY HAVING SELECT ORDER BY
SELECT CAR_ID,
    CASE
        WHEN CAR_ID IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                       WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
